services:
  bandwidth-hero-proxy:
    container_name: bandwidth-hero-proxy
    image: docker.io/energypatrikhu/bandwidth-hero-proxy-go
    network_mode: bridge
    # environment: # optional environment variables
    #   BHP_PORT: 80
    #   BHP_FLARESOLVERR_URL: "http://flaresolverr:8191"
    #   BHP_VERBOSE_LOGGING: false
    #   BHP_VIPS_MAX_CONCURRENCY: 4 # default: number of CPU cores
    #   BHP_IGNORE_SIZE_CHECK: false
    #   BHP_TARGET_FORMAT: "" # Available formats: "webp", "jpeg", "jxl"
    #   BHP_AUTO_REDUCE_QUALITY: false
    #   BHP_AUTO_SELECT_FORMAT: true
    #   BHP_AUTO_SELECT_FORMAT_LIST: ["jxl", "webp", "jpeg"]
    #   BHP_PASSTHROUGH_ANIMATED: false
    #   BHP_EXTERNAL_REQUEST_TIMEOUT: "60s"
    #   BHP_EXTERNAL_REQUEST_RETRIES: 5
    #   BHP_EXTERNAL_REQUEST_REDIRECTS: 10
    #   BHP_EXTERNAL_REQUEST_OMIT_HEADERS: ""
    #   # Webp options
    #   BHP_WEBP_LOSSLESS: false
    #   BHP_WEBP_EFFORT: 4
    #   BHP_WEBP_SMART_SUBSAMPLE: true
    #   BHP_WEBP_SMART_DEBLOCK: true
    #   BHP_WEBP_PASSES: 1
    #   # Jpeg options
    #   BHP_JPEG_OPTIMIZE_CODING: true
    #   BHP_JPEG_OPTIMIZE_SCANS: true
    #   BHP_JPEG_INTERLACE: true
    #   BHP_JPEG_TRELLIS_QUANT: true
    #   BHP_JPEG_OVERSHOOT_DERINGING: true
    #   BHP_JPEG_QUANT_TABLE: 3
    #   # Jxl options
    #   BHP_JXL_TIER: 0
    #   BHP_JXL_EFFORT: 7
    #   BHP_JXL_LOSSLESS: false
    ports:
      - 8080:80
